# Generated by Django 4.1 on 2022-08-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(blank=True, max_length=100)),
                ('tokenExpiration', models.IntegerField(blank=True)),
                ('refreshToken', models.CharField(blank=True, max_length=100)),
                ('stravaCreatedAt', models.DateField(blank=True)),
                ('prDistance', models.IntegerField(default=1000)),
                ('prTime', models.IntegerField(default=300)),
                ('unitPreference', models.CharField(choices=[('M', 'Metric'), ('I', 'Imperial')], max_length=1)),
                ('polyline', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stravaId', models.IntegerField()),
                ('averageHr', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('intensity', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=500)),
                ('startLat', models.CharField(blank=True, max_length=25)),
                ('startLng', models.CharField(blank=True, max_length=25)),
                ('shareableKey', models.CharField(blank=True, max_length=100)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.athlete')),
            ],
        ),
    ]
