# Generated by Django 4.1 on 2022-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_athlete_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='tokenExpiration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
