# Generated by Django 4.1 on 2022-08-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_athlete_tokenexpiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='stravaCreatedAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
