# Generated by Django 4.1 on 2022-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_athlete_stravacreatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='stravaId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
