# Generated by Django 4.1 on 2022-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_athlete_stravaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='averageHr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startLat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startLng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=25, null=True),
        ),
    ]
