# Generated by Django 4.1 on 2022-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_activity_averagehr_alter_activity_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='stravaId',
            field=models.BigIntegerField(),
        ),
    ]
