# Generated by Django 4.1 on 2022-08-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_activity_stravaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='polyline',
        ),
    ]
