# Generated by Django 4.1 on 2022-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_athlete_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='stravaId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
