# Generated by Django 4.1 on 2022-08-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_activity_stravaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='shareableKey',
        ),
    ]
