# Generated by Django 4.1 on 2022-08-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_activity_shareablekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='stravaCreatedAt',
        ),
    ]
