# Generated by Django 4.1 on 2022-08-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_athlete_stravacreatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='intensity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
