# Generated by Django 4.1 on 2022-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_activity_intensity_remove_activity_startlat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
