# Generated by Django 4.1.1 on 2023-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
