# Generated by Django 4.1.1 on 2023-01-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_activity_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
